### ISSUE TITLE
I run into some errors when running main.py

### ISSUE THREAD

**Issue by Shuntw6096** [seulkiyeom/LRP_Pruning_toy_example#2] opened 2021-06-20 13:11 UTC
I test it on colab.
1. You need to put an ```__init__.py``` under  ```module``` or Python won't find module.
2. And all Korean text in the code will cause ```SyntaxError```.
```
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    from modules.prune import prune_layer_toy
  File "/content/LRP_Pruning_toy_example/modules/prune.py", line 30
SyntaxError: Non-ASCII character '\xec' in file /content/LRP_Pruning_toy_example/modules/prune.py on line 30, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```
3. 
```
Traceback (most recent call last):
  File "main.py", line 1012, in <module>
    noisy_test=args.noisytest)
  File "main.py", line 240, in __init__
    self.log_file           = open(self.log_file, 'ta')
ValueError: mode string must begin with one of 'r', 'w', 'a' or 'U', not 'ta'  File "main.py", line 1012, in <module>
```
Thanks

**Comment by sebastian-lapuschkin** [comment] 2021-06-21 09:50
Dear @Shuntw6096 ,

I agree with 1. , and also removed `__pycache__` in `modules`. This has been fixed in b3762f3.

However, we primarily created this scripts for local use, and could not replicate your issues when installing everything as intended (i.e. following install_conda.sh) in Python 3.5 and Python 3.9 .

It would be good to get some additional info on the environment you are running in colab. Your output wrt issue number 3 very much looks to me that you are within a Python 2.* - based envionment. If that is the case, please switch to Python 3.  Official support for Python2 ended in 2019, and I also do not intend to implement legacy support for Python 2 in this repo.

best

**Comment by Shuntw6096** [comment] 2021-06-23 12:18
Hi, Thanks for your reply, but 
https://github.com/seulkiyeom/LRP_Pruning_toy_example/blob/b3762f3ce69a36c811423d392f7eb374ba0ca867/main.py#L238
really makes ```ValueError``` when I run code in my local, I use python 3.7.10, I changed it to `a` (append mode, or `a+`) and it work normally.
```
Traceback (most recent call last):
  File "main.py", line 1012, in <module>
    noisy_test=args.noisytest)
  File "main.py", line 240, in __init__
    self.log_file           = open(self.log_file, 'ta')
ValueError: mode string must begin with one of 'r', 'w', 'a' or 'U', not 'ta'  File "main.py", line 1012, in <module>
```
By the way, Pruning by explaining is a nice work.
Thanks

**Comment by sebastian-lapuschkin** [comment] 2021-06-23 12:27
hi @Shuntw6096 ,

that's weird. I am sorry I can not replicate the issue and help any further, but I am glad you got it to work.
'ta' should be fine, but 't' is the default and not strictly necessary: https://docs.python.org/3/library/functions.html?highlight=open#open

closing this.
best

**Closed as completed by sebastian-lapuschkin** 2021-06-23 12:27 UTC
